### ISSUE TITLE
targetPlatform with openjfx

### ISSUE THREAD

**Issue by GarryMoveOut** [beryx-gist/badass-jlink-example-log4j2-javafx#1]
I have problem in my project which is using badass-jlink gradle plugin and openjfx. When I build custom runtime image on Linux for Windows, I can not run it on targeted platform. 
To check it I cloned this gist to my Linux. I added two lines to build.gradle:
```
jlink {
    javaHome = '/usr/lib64/open_jdk'
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    targetPlatform('win-x64', '/home/damian/win/jdk-11.0.1/')
    launcher {
        name = 'helloFX'
    }
    forceMerge('log4j-api')
}
```
Image is build without error but when I run launcher on Windows I got exception (probably caused by lack of openjfx libraries or modules):

> Graphics Device initialization failed for :  d3d, sw
> Error initializing QuantumRenderer: no suitable pipeline found
> java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
>         at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(Unknown Source)
>         at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.init(Unknown Source)
>         at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
>         at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
> Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
>         at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(Unknown Source)
>         at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(Unknown Source)
>         at java.base/java.lang.Thread.run(Unknown Source)
> Exception in thread "main" java.lang.reflect.InvocationTargetException
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
>         at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
> Caused by: java.lang.RuntimeException: No toolkit found
>         at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
>         ... 5 more 

I don't know is the problem appear in reverse conditions.

**Comment by siordache** [comment]
When building a custom runtime image on Linux for Windows, your dependencies need to include the Windows-specific OpenJFX artifacts. However, the `org.openjfx.javafxplugin` always configures your dependencies with the OpenJFX artifacts of the platform on which Gradle runs.

To avoid this, you should no longer use the `org.openjfx.javafxplugin`.  Instead, use the `org.javamodularity.moduleplugin` and put the windows-specific OpenJFX artifacts in the `dependencies` block.

The resulting `build.gradle` should look like this:

```
plugins {
    id 'application'
    id 'org.javamodularity.moduleplugin' version '1.4.0'
    id 'org.beryx.jlink' version '2.3.0'
}

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.apache.logging.log4j:log4j-core:2.11.1'
    compile 'org.openjfx:javafx-base:11:win'
    compile 'org.openjfx:javafx-controls:11:win'
    compile 'org.openjfx:javafx-fxml:11:win'
    compile 'org.openjfx:javafx-graphics:11:win'
}

mainClassName = "hellofx/org.openjfx.HelloFX"

jlink {
    javaHome = '/usr/lib64/open_jdk'
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    targetPlatform('win-x64', '/home/damian/win/jdk-11.0.1/')
    launcher {
        name = 'helloFX'
    }
    forceMerge('log4j-api')
}
```

**Comment by GarryMoveOut** [comment]
Thank you it is working
