### ISSUE TITLE
How to read external log4j2 configuration on jlink image?

### ISSUE THREAD

**Issue by swardana** [beryx-gist/badass-jlink-example-log4j2-javafx#4]
Hey, this is not an issue report, but more into question.

In jlinked application how we could support external log4j2 configuration?

I know that we could define jvmArgs on launcher

```
jlink {
    launcher {
        jvmArgs = ['-Dlog4j.configurationFile=./log4j2.xml']
    }
}
```

My question is should the log4j2.xml store inside jlink image or it could read outside jlink image?

Sorry to make a question on here, but hoping someone could give good explanation for this.

**Comment by siordache** [comment]
The log4j2.xml could reside outside the jlink image, but in this case:
- the user is responsible to make log4j2.xml available at the required location
- a hard-coded location for log4j2.xml may be problematic for some users. You can make the location configurable using an environment variable:
    ```
    launcher {
         jvmArgs = ['-Dlog4j.configurationFile={{MY_APP_LOG_DIR}}/log4j2.xml']
    }
    ```
    The user is then responsible to set the MY_APP_LOG_DIR environment variable and to place the log4j2.xml file at this location.

**Comment by swardana** [comment]
Hi @siordache 
Thanks for the answer, then it's correct that the we could use path environment using `{{VARIABLE_NAME}}` on the jvmArgs value?

If yes this will solve my problem, because I'm thinking to create configuration like below:

```
launcher {
     jvmArgs = ['-Dlog4j.configurationFile={{sys:user.home}}/.myapp/log4j2.xml']
}
```

**Comment by siordache** [comment]
The syntax `{{sys:user.home}}` is not supported. Only environment variables are allowed, not system properties.

In version 2.22.4 I added the special placeholder `{{HOME_DIR}}`, which is replaced by the plugin with the environment variable `HOME` for Linux-like systems and with `USERPROFILE` for Windows. So, you can use now:
```
launcher {
     jvmArgs = ['-Dlog4j.configurationFile={{HOME_DIR}}/.myapp/log4j2.xml']
}
```

**Comment by swardana** [comment]
Interesting, I think at the moment it's enough for my apps.
Thank you for the answer
